import type { Metadata } from "next";
import "./globals.css";
import ResponsiveNabBar from "@/composant/Navbar/ResponsiveNabBar";
import Footer from "@/composant/Footer/Footer";

export const metadata: Metadata = {
  title: "BookStore",
  description: "Generated by Nour",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ResponsiveNabBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
